### ISSUE TITLE
ERROR: Samba does not appear to support kerberos.

### ISSUE THREAD

**Issue by mikedep333** [dell-oss/vasidmapd#1]
I am running RHEL 7.1 GA (released earlier this week) with Samba `4.1.12-21.el7_1`, quest-vasidmap `1.2.6-1` and Authentication Services `4.1.0.21518`. I have not modified this RHEL 7.1 Samba package in anyway. It is safe to assume that it does support Kerberos.

When I run /opt/quest/sbin/vas-samba-config I get the error:
>        ERROR: Samba does not appear to support kerberos.
>        Please validate that your version of samba supports
>        kerberos by checking the build settings on smbd by
>        running /usr/sbin/smbd -b and looking for 
>        WITH_ADS under the "--with Options" or "Build Options"
>        sections.

When I run `/usr/sbin/smbd -b` I see `WITH_ADS` under `--with Options` but not under `Build Options`.

It appears that vas-samba-config is checking for that string twice rather than once:
>if [ `$samba_prefix/sbin/smbd -b | grep WITH_ADS | wc -l` -eq "2" ]; then
>  with_ads_support=true
>fi

**Comment by TomGem** [comment]
Hi Mike,

I had the same problem running Ubuntu 14.04.2 LTS:

`# vas-samba-config -V`
`1.2.6`
`# smbd --version`
`Version 4.1.6-Ubuntu`
`# smbd -b | grep WITH_ADS`
`   WITH_ADS`


After changing line 107 to `-eq "1"` vas-samba-config worked fine.

Thank you for the hint!

**Comment by JaysonHurst** [comment]
On some systems the "WITH_ADS" can show up under both --with options and under the Build Options section.  Perhaps a better fix would be to check on 107 for -ge "1" to account for a system where it only shows up under --with options and for those that it shows up under Build options as well.

**Comment by JaysonHurst** [comment]
This has been fixed as RC bug 854.
